Using custom data configuration default-b1438bda5d0b9219
  0%|          | 0/1 [00:00<?, ?it/s]100%|██████████| 1/1 [00:00<00:00, 3236.35it/s]
  0%|          | 0/1 [00:00<?, ?it/s]100%|██████████| 1/1 [00:00<00:00, 458.69it/s]
Failed to read file '/home/qiyuan/DSI-CS5430/data/NQ/NQ_10k_multi_task_train_semantic_ids2.json' with error <class 'pyarrow.lib.ArrowInvalid'>: JSON parse error: Missing a closing quotation mark in string. in row 4
Traceback (most recent call last):
  File "/home/qiyuan/.conda/envs/dsi/lib/python3.8/site-packages/datasets/packaged_modules/json/json.py", line 144, in _generate_tables
    dataset = json.load(f)
  File "/home/qiyuan/.conda/envs/dsi/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/home/qiyuan/.conda/envs/dsi/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/home/qiyuan/.conda/envs/dsi/lib/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 8012)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 216, in <module>
    main()
  File "train.py", line 116, in main
    train_dataset = IndexingTrainDataset(path_to_data=args.train_data,
  File "/home/qiyuan/DSI-CS5430/data.py", line 60, in __init__
    self.train_data = datasets.load_dataset(
  File "/home/qiyuan/.conda/envs/dsi/lib/python3.8/site-packages/datasets/load.py", line 1702, in load_dataset
    builder_instance.download_and_prepare(
  File "/home/qiyuan/.conda/envs/dsi/lib/python3.8/site-packages/datasets/builder.py", line 594, in download_and_prepare
    self._download_and_prepare(
  File "/home/qiyuan/.conda/envs/dsi/lib/python3.8/site-packages/datasets/builder.py", line 683, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "/home/qiyuan/.conda/envs/dsi/lib/python3.8/site-packages/datasets/builder.py", line 1133, in _prepare_split
    for key, table in utils.tqdm(
  File "/home/qiyuan/.conda/envs/dsi/lib/python3.8/site-packages/tqdm/std.py", line 1169, in __iter__
    for obj in iterable:
  File "/home/qiyuan/.conda/envs/dsi/lib/python3.8/site-packages/datasets/packaged_modules/json/json.py", line 146, in _generate_tables
    raise e
  File "/home/qiyuan/.conda/envs/dsi/lib/python3.8/site-packages/datasets/packaged_modules/json/json.py", line 122, in _generate_tables
    pa_table = paj.read_json(
  File "pyarrow/_json.pyx", line 308, in pyarrow._json.read_json
  File "pyarrow/error.pxi", line 154, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 91, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: JSON parse error: Missing a closing quotation mark in string. in row 4
